# Generated by Django 2.2.4 on 2019-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_musicrid', models.IntegerField()),
                ('music_name', models.CharField(max_length=200)),
                ('music_artist', models.CharField(max_length=200)),
                ('music_releasedate', models.CharField(max_length=200)),
                ('music_artistid', models.IntegerField()),
                ('music_album', models.CharField(max_length=200)),
                ('music_alnumind', models.IntegerField()),
                ('music_src', models.CharField(max_length=200)),
                ('music_lrc_src', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.IntegerField()),
                ('singer_name', models.CharField(max_length=200)),
                ('singer_music_num', models.IntegerField()),
                ('singer_listen', models.IntegerField()),
                ('singer_like', models.IntegerField()),
                ('singer_pic', models.CharField(max_length=200)),
                ('singer_aartist', models.CharField(max_length=200)),
                ('singer_isstar', models.IntegerField()),
                ('singer_prefix', models.CharField(default='', max_length=200)),
                ('singer_ishot', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
